# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b92e529a621eb09676511bb0ab7ca0a6364c100e4eb62dfee1c9b0a3d6dd9764d223248d3a5f410af587bf3fe09d6219b898157f1d51c6b139e622194dde4d5

test:
  secret_key_base: 9d5ca00f42da27a4749c1d926a684173a250d14c04558bedd7b3fbdb4f5d289c80acc473422022eb32b6bf09dc5d9e4536ddf1f80f3cb1906a25014815386b81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
